name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0
      - name: Install dependencies, build, and test
        run: bun install
      - run: bunx playwright install chromium
      - run: bunx playwright install firefox
      - run: bunx playwright install webkit
      - run: bun run build
      - run: bun run bundlewatch
      - run: bun run test
